
class PrimordialClicker extends BaseGame{
  constructor(){ super('primordial-clicker','Primordial Clicker'); this.canvas.addEventListener('pointerdown',e=>this.pick(e)); }
  rewardWin(message,reward,bonus=2000){ if(this.over)return; this.score+=bonus; StorageManager.saveAchievement(this.gameId,'reward-primordial-singularity','Reward: '+reward); AudioEngine.play('reward'); this.win(message+' — Reward: '+reward); }
  reset(){ this.atp=0; this.rate=0; this.tier=0; this.clickPower=1; this.lives=1; this.upgrades=[['Flagella',25,1],['Photosynthesis',80,2],['Multicellular',180,3],['Nervous System',420,5],['Tools',900,8],['Language',1800,13],['Cities',3600,21],['Singularity',7200,34]]; this.bought={}; this.eventTimer=16; }
  pick(e){ if(this.over||this.paused) return; const p=this.pointer(e); if(Math.hypot(p.x-250,p.y-290)<95){ this.atp+=this.clickPower; this.score+=this.clickPower; this.particles.push(...Utils.makeParticles(p.x,p.y,3,'#36e28f')); AudioEngine.play('coin'); } for(let i=0;i<this.upgrades.length;i++){ const x=475,y=92+i*54,w=260,h=42; if(p.x>x&&p.x<x+w&&p.y>y&&p.y<y+h) this.buy(i); } }
  buy(i){ const [name,cost,boost]=this.upgrades[i]; if(this.bought[i]||this.atp<cost) { AudioEngine.play('warning'); return; } if(i>0&&!this.bought[i-1]){ AudioEngine.play('failure'); return; } this.atp-=cost; this.bought[i]=true; this.tier=i+1; this.rate+=boost; this.clickPower+=Math.ceil(boost/2); this.score+=cost; AudioEngine.play('powerup'); if(i===this.upgrades.length-1) this.rewardWin('Life reached technological singularity','Primordial Singularity Core',3000); }
  update(dt){ this.atp+=this.rate*dt; this.eventTimer-=dt; if(this.eventTimer<=0){ this.eventTimer=18+Math.random()*12; const bonus=50+this.tier*25; this.atp+=bonus; this.toast='Oxygen spike: +'+bonus+' ATP'; AudioEngine.play('success'); } this.updateHUD({ATP:Math.floor(this.atp),Rate:`${this.rate.toFixed(1)}/s`,Tier:`${this.tier}/8`,Goal:'Unlock Singularity',Reward:'Primordial Singularity Core'}); }
  draw(){ const c=this.ctx; c.fillStyle='#061020'; c.fillRect(0,0,800,600); const era=['Microbe','Flagella','Photosynthesis','Multicellular','Nerves','Tools','Language','Cities','Singularity'][this.tier]; c.fillStyle='#cbd7ff'; c.font='bold 22px system-ui'; c.fillText('Era: '+era,90,64); c.fillStyle='#16344a'; c.beginPath(); c.arc(250,290,100+Math.sin(this.elapsed*3)*6,0,Math.PI*2); c.fill(); c.fillStyle=['#36e28f','#18e0ff','#ffd166','#ff4d6d'][this.tier%4]; c.beginPath(); c.arc(250,290,72+this.tier*4,0,Math.PI*2); c.fill(); c.fillStyle='#071020'; c.font='bold 20px system-ui'; c.textAlign='center'; c.fillText('CLICK ATP',250,298); c.textAlign='left'; c.fillStyle='#9fb3ff'; c.fillText(this.toast||'Spend ATP through the evolution tree.',95,525);
    for(let i=0;i<this.upgrades.length;i++){ const [name,cost]=this.upgrades[i], x=475,y=92+i*54,w=260,h=42; const ok=this.bought[i], can=this.atp>=cost&&(i===0||this.bought[i-1]); c.fillStyle=ok?'#36e28f':can?'#1e4462':'#1b2436'; c.fillRect(x,y,w,h); c.strokeStyle='#ffffff33'; c.strokeRect(x,y,w,h); c.fillStyle=ok?'#071020':'#fff'; c.font='bold 15px system-ui'; c.fillText((ok?'✓ ':'')+name,x+12,y+25); c.fillText(cost+' ATP',x+170,y+25); }
  }
}
window.currentGame=new PrimordialClicker(); window.currentGame.start();
