
class VortexCommand extends BaseGame {
  constructor(){ super('vortex-command','Vortex Command'); this.canvas.addEventListener('pointerdown',()=>this.fire()); }
  reset(){ this.ship={x:0,y:0,z:1,shield:3,heat:0}; this.score=0; this.lives=3; this.level=1; this.wave=1; this.mult=1; this.lasers=[]; this.objects=[]; this.stars=Array.from({length:180},()=>({x:(Math.random()-.5)*90,y:(Math.random()-.5)*60,z:Math.random()*45+5})); this.spawnTimer=0; this.carrier=null; this.flare=3; this.targetKills=0; this.spawnWave(); }
  spawnWave(){ for(let i=0;i<8+this.wave*2;i++) this.spawnAsteroid(); for(let i=0;i<2+this.wave;i++) this.spawnFighter(); if(this.wave>=5&&!this.carrier){ this.carrier={x:0,y:-3,z:45,hp:900,max:900,phase:0}; } }
  spawnAsteroid(){ const size=Utils.choice([1,2,3]); this.objects.push({kind:'asteroid',x:(Math.random()-.5)*38,y:(Math.random()-.5)*24,z:55+Math.random()*35,r:size*0.7,hp:size*40,size,rot:Math.random()*6,spin:(Math.random()-.5)*2}); }
  spawnFighter(){ this.objects.push({kind:'fighter',x:(Math.random()-.5)*34,y:(Math.random()-.5)*18,z:65+Math.random()*28,r:.8,hp:80,phase:Math.random()*6,shot:1+Math.random()*2}); }
  project(o){ const z=Math.max(1,o.z); const s=440/z; return {x:400+(o.x-this.ship.x)*s,y:300+(o.y-this.ship.y)*s,s}; }
  update(dt){
    let vx=0,vy=0;if(this.input.isPressed('left'))vx-=1;if(this.input.isPressed('right'))vx+=1;if(this.input.isPressed('up'))vy-=1;if(this.input.isPressed('down'))vy+=1; const l=Math.hypot(vx,vy)||1; this.ship.x=Utils.clamp(this.ship.x+vx/l*18*dt,-12,12); this.ship.y=Utils.clamp(this.ship.y+vy/l*12*dt,-8,8); this.ship.heat=Math.max(0,this.ship.heat-dt*.35); if(this.input.isPressed('action'))this.fire();
    for(const st of this.stars){ st.z-=24*dt; if(st.z<1){ st.z=50; st.x=(Math.random()-.5)*90; st.y=(Math.random()-.5)*60; } }
    this.spawnTimer-=dt; if(this.spawnTimer<=0){ this.spawnTimer=1.7; if(this.objects.length<22) Math.random()<.55?this.spawnAsteroid():this.spawnFighter(); }
    for(const o of this.objects){ o.z-= (o.kind==='fighter'?9:13)*dt; o.rot=(o.rot||0)+(o.spin||1)*dt; if(o.kind==='fighter'){ o.phase+=dt; o.x+=Math.sin(o.phase*1.6)*dt*2; o.shot-=dt; if(o.shot<=0){ o.shot=1.8; this.objects.push({kind:'missile',x:o.x,y:o.y,z:o.z-1,r:.35,hp:1,vx:(this.ship.x-o.x)*.15,vy:(this.ship.y-o.y)*.15}); AudioEngine.play('warning'); }} if(o.kind==='missile'){ o.x+=o.vx*dt*8; o.y+=o.vy*dt*8; o.z-=22*dt; } if(o.z<1.2){ if(Math.hypot(o.x-this.ship.x,o.y-this.ship.y)<(o.kind==='missile'?5:3+o.r)){ this.hit(); } o.dead=true; }}
    if(this.carrier){ this.carrier.phase+=dt; this.carrier.z=Math.max(20,this.carrier.z-1.2*dt); this.carrier.x=Math.sin(this.carrier.phase*.4)*5; if(Math.random()<dt*.7) this.spawnFighter(); }
    for(const b of this.lasers){ b.z+=70*dt; b.life-=dt; for(const o of this.objects){ if(o.dead||o.kind==='missile') continue; const dz=Math.abs(o.z-b.z); if(dz<2 && Math.hypot(o.x-b.x,o.y-b.y)<o.r+1.1){ o.hp-=b.dmg; b.life=0; if(o.hp<=0){ o.dead=true; this.targetKills++; this.score+=Math.floor((o.kind==='fighter'?400:160*o.size)*this.mult); this.mult=Math.min(8,this.mult+.25); AudioEngine.play('explosion'); if(o.kind==='asteroid'&&o.size>1){ for(let k=0;k<2;k++) this.objects.push({kind:'asteroid',x:o.x+(Math.random()-.5)*2,y:o.y+(Math.random()-.5)*2,z:o.z+2,r:(o.size-1)*.7,hp:(o.size-1)*40,size:o.size-1,rot:Math.random()*6,spin:(Math.random()-.5)*3}); } } else AudioEngine.play('success'); }}
      if(this.carrier&&Math.abs(this.carrier.z-b.z)<3&&Math.hypot(this.carrier.x-b.x,this.carrier.y-b.y)<8){ this.carrier.hp-=b.dmg; b.life=0; this.score+=Math.floor(90*this.mult); if(this.carrier.hp<=0){ this.score+=10000; StorageManager.saveAchievement(this.gameId,'vortex-carrier-breaker','Reward: Vortex Carrier Breaker'); this.win('Carrier destroyed — Reward: Vortex Carrier Breaker'); } }}
    this.objects=this.objects.filter(o=>!o.dead&&o.z<100); this.lasers=this.lasers.filter(b=>b.life>0&&b.z<95); if(this.targetKills>=12*this.wave&&this.wave<5){ this.wave++; this.level=this.wave; this.targetKills=0; this.spawnWave(); AudioEngine.play('reward'); }
    this.updateHUD({Shield:this.ship.shield,Heat:`${Math.floor(this.ship.heat*100)}%`,Wave:this.carrier?'Carrier':`${this.wave}/5`,Multiplier:`${this.mult.toFixed(1)}x`,Flares:this.flare,Goal:'Destroy carrier',Reward:'Vortex Carrier Breaker'});
  }
  fire(){ if(this.ship.heat>.95||this.over||this.paused) return; this.ship.heat+=.08; this.lasers.push({x:this.ship.x-.55,y:this.ship.y,z:2,life:1.1,dmg:32}); this.lasers.push({x:this.ship.x+.55,y:this.ship.y,z:2,life:1.1,dmg:32}); AudioEngine.play('shoot'); }
  handleAction(a){ if(a==='action')this.fire(); if(a==='secondary'&&this.flare>0){ this.flare--; for(const o of this.objects) if(o.kind==='missile'&&o.z<25) o.dead=true; this.particles.push(...Utils.makeParticles(400,300,30,'#ffd166')); AudioEngine.play('powerup'); } }
  hit(){ this.ship.shield--; this.mult=1; AudioEngine.play('failure'); if(this.ship.shield<=0){ this.lives=0; this.gameOver('Vortex destroyed — carrier escaped'); } }
  drawAsteroid(c,p,o){ c.save(); c.translate(p.x,p.y); c.rotate(o.rot); c.strokeStyle='#a9b4d8'; c.lineWidth=Math.max(1,p.s*o.r*.04); c.beginPath(); const n=9; for(let i=0;i<n;i++){ const a=i*Math.PI*2/n; const rr=p.s*o.r*(.7+.25*Math.sin(i*2+o.rot)); const x=Math.cos(a)*rr,y=Math.sin(a)*rr; if(i)c.lineTo(x,y); else c.moveTo(x,y); } c.closePath(); c.stroke(); c.restore(); }
  draw(){ const c=this.ctx; const bg=c.createLinearGradient(0,0,0,600); bg.addColorStop(0,'#02030c'); bg.addColorStop(.5,'#071530'); bg.addColorStop(1,'#05020c'); c.fillStyle=bg; c.fillRect(0,0,800,600);
    for(const st of this.stars){ const p=this.project(st); c.globalAlpha=Utils.clamp(1-st.z/55,.15,1); c.fillStyle='#dff7ff'; c.fillRect(p.x,p.y,Math.max(1,2*p.s/30),Math.max(1,2*p.s/30)); } c.globalAlpha=1;
    const all=[...this.objects]; if(this.carrier) all.push({kind:'carrier',...this.carrier}); all.sort((a,b)=>b.z-a.z);
    for(const o of all){ const p=this.project(o); if(p.x<-80||p.x>880||p.y<-80||p.y>680) continue; if(o.kind==='asteroid') this.drawAsteroid(c,p,o); else if(o.kind==='fighter'){ c.save(); c.translate(p.x,p.y); c.scale(p.s*.035,p.s*.035); c.fillStyle='#ff4d6d'; c.shadowBlur=14; c.shadowColor='#ff4d6d'; c.beginPath(); c.moveTo(0,-18); c.lineTo(24,18); c.lineTo(0,8); c.lineTo(-24,18); c.closePath(); c.fill(); c.restore(); } else if(o.kind==='missile'){ c.fillStyle='#ffd166'; c.shadowBlur=18; c.shadowColor='#ffd166'; c.beginPath(); c.arc(p.x,p.y,Math.max(3,p.s*.04),0,Math.PI*2); c.fill(); c.shadowBlur=0; } else if(o.kind==='carrier'){ c.save(); c.translate(p.x,p.y); c.scale(p.s*.035,p.s*.035); c.fillStyle='#7c5cff'; c.shadowBlur=26; c.shadowColor='#7c5cff'; c.fillRect(-120,-28,240,56); c.fillStyle='#18e0ff'; c.fillRect(-80,-46,160,20); c.fillStyle='#ff4d6d'; c.fillRect(-100,-72,200*(o.hp/o.max),10); c.restore(); } }
    for(const b of this.lasers){ const p=this.project(b), p2=this.project({x:b.x,y:b.y,z:b.z+5}); c.strokeStyle='#18e0ff'; c.lineWidth=3; c.beginPath(); c.moveTo(p.x,p.y); c.lineTo(p2.x,p2.y); c.stroke(); }
    // ship cockpit
    c.save(); c.translate(400+this.ship.x*12,515+this.ship.y*8); c.shadowBlur=22; c.shadowColor='#18e0ff'; c.fillStyle='#14234f'; c.beginPath(); c.moveTo(0,-48); c.lineTo(54,28); c.lineTo(16,16); c.lineTo(0,42); c.lineTo(-16,16); c.lineTo(-54,28); c.closePath(); c.fill(); c.fillStyle='#18e0ff'; c.fillRect(-32,22,18,6); c.fillRect(14,22,18,6); c.restore(); c.strokeStyle='#fff'; c.beginPath(); c.arc(400,300,12,0,Math.PI*2); c.moveTo(380,300); c.lineTo(420,300); c.moveTo(400,280); c.lineTo(400,320); c.stroke(); }
}
window.currentGame=new VortexCommand(); window.currentGame.start();
