class AsteroidsHD extends BaseGame {
  rewardWin(message, reward, bonus=250){ if(this.over) return; this.score += bonus; StorageManager.saveAchievement(this.gameId, 'reward-'+reward.toLowerCase().replace(/[^a-z0-9]+/g,'-'), 'Reward: '+reward); this.win(message + ' — Reward: ' + reward); }

  reset(){ this.ship={x:400,y:300,a:-Math.PI/2,vx:0,vy:0,r:14,cd:0,inv:.8}; this.bullets=[]; this.rocks=[]; this.spawnWave(); this.lives=3; this.score=0; this.level=1; }
  spawnWave(){ this.rocks=[]; for(let i=0;i<4+this.level;i++){ let edge=i%4; let x=edge<2?Math.random()*800:(edge===2?0:800); let y=edge<2?(edge===0?0:600):Math.random()*600; this.rocks.push(this.makeRock(x,y,34+Math.random()*20)); } }
  makeRock(x,y,r){ let a=Math.random()*Math.PI*2, s=30+Math.random()*45+this.level*4; return {x,y,r,vx:Math.cos(a)*s,vy:Math.sin(a)*s,spin:(Math.random()-.5)*2,ang:0}; }
  shoot(){ if(this.ship.cd>0) return; this.bullets.push({x:this.ship.x+Math.cos(this.ship.a)*18,y:this.ship.y+Math.sin(this.ship.a)*18,vx:Math.cos(this.ship.a)*440+this.ship.vx,vy:Math.sin(this.ship.a)*440+this.ship.vy,life:.9}); this.ship.cd=.18; AudioEngine.play('shoot'); }
  handleAction(a){ if(a==='action') this.shoot(); if(a==='secondary') this.ship.vx*=.6,this.ship.vy*=.6; }
  update(dt){ let s=this.ship; if(this.input.isPressed('left')) s.a-=4.4*dt; if(this.input.isPressed('right')) s.a+=4.4*dt; if(this.input.isPressed('up')){ s.vx+=Math.cos(s.a)*230*dt; s.vy+=Math.sin(s.a)*230*dt; this.particles.push(...Utils.makeParticles(s.x-Math.cos(s.a)*15,s.y-Math.sin(s.a)*15,1,'#ffcf6b')); } s.vx*=.992; s.vy*=.992; s.x=(s.x+s.vx*dt+800)%800; s.y=(s.y+s.vy*dt+600)%600; s.cd=Math.max(0,s.cd-dt); s.inv=Math.max(0,s.inv-dt);
    for(const b of this.bullets){ b.x=(b.x+b.vx*dt+800)%800; b.y=(b.y+b.vy*dt+600)%600; b.life-=dt; } this.bullets=this.bullets.filter(b=>b.life>0);
    for(const r of this.rocks){ r.x=(r.x+r.vx*dt+800)%800; r.y=(r.y+r.vy*dt+600)%600; r.ang+=r.spin*dt; }
    for(const b of [...this.bullets]) for(const r of [...this.rocks]) if(Math.hypot(b.x-r.x,b.y-r.y)<r.r){ this.bullets.splice(this.bullets.indexOf(b),1); this.rocks.splice(this.rocks.indexOf(r),1); this.score+=Math.floor(90-r.r); this.particles.push(...Utils.makeParticles(r.x,r.y,18,'#18e0ff')); AudioEngine.play('explosion'); if(r.r>24){ this.rocks.push(this.makeRock(r.x,r.y,r.r*.55),this.makeRock(r.x,r.y,r.r*.55)); } break; }
    if(s.inv<=0) for(const r of this.rocks) if(Math.hypot(s.x-r.x,s.y-r.y)<s.r+r.r*.75){ this.lives--; s.x=400;s.y=300;s.vx=s.vy=0;s.inv=1.2; AudioEngine.play('failure'); if(this.lives<=0) this.gameOver('Ship Destroyed'); break; }
    if(!this.rocks.length){ this.score+=500; if(this.level>=3){ this.rewardWin('Sector 3 Cleared', 'Sector Guardian Medal', 1000); return; } this.level++; this.spawnWave(); AudioEngine.play('success'); } this.updateHUD({Asteroids:this.rocks.length, Goal:'Clear 3 sectors', Reward:'Sector Guardian Medal'}); }
  draw(){ const c=this.ctx,s=this.ship; c.strokeStyle='#18e0ff'; c.lineWidth=2; for(const r of this.rocks){ c.save(); c.translate(r.x,r.y); c.rotate(r.ang); c.beginPath(); for(let i=0;i<10;i++){ let a=i/10*Math.PI*2, rr=r.r*(.82+((i*17)%5)/12); c[i?'lineTo':'moveTo'](Math.cos(a)*rr,Math.sin(a)*rr); } c.closePath(); c.stroke(); c.restore(); } c.fillStyle='#ffcf6b'; for(const b of this.bullets)c.fillRect(b.x-2,b.y-2,4,4); c.save(); c.translate(s.x,s.y); c.rotate(s.a); c.globalAlpha=s.inv>0?.55+Math.sin(this.elapsed*30)*.25:1; c.strokeStyle='#fff'; c.beginPath(); c.moveTo(20,0); c.lineTo(-14,-12); c.lineTo(-9,0); c.lineTo(-14,12); c.closePath(); c.stroke(); c.restore(); }
}
document.addEventListener('DOMContentLoaded',()=>{ window.currentGame=new AsteroidsHD('asteroids-hd','Asteroids HD'); window.currentGame.start(); });
