
class LexicalDrift extends BaseGame{
  constructor(){ super('lexical-drift','Lexical Drift'); this.keyBuffer=''; window.addEventListener('keydown',e=>this.key(e)); this.canvas.addEventListener('pointerdown',e=>this.pick(e)); }
  rewardWin(message,reward,bonus=900){ if(this.over)return; this.score+=bonus; StorageManager.saveAchievement(this.gameId,'reward-lexical-drift','Reward: '+reward); AudioEngine.play('reward'); this.win(message+' — Reward: '+reward); }
  reset(){ this.puzzles=[['COLD','WARM',['CORD','WORD','WARD','WARM']],['HEAD','TAIL',['HEAL','TEAL','TELL','TALL','TAIL']],['GAME','CODE',['GATE','CATE','CADE','CODE']]]; this.pi=0; this.current=this.puzzles[0][0]; this.target=this.puzzles[0][1]; this.path=[this.current]; this.keyBuffer=''; this.lives=3; this.score=0; this.dictionary=new Set(['COLD','CORD','WORD','WARD','WARM','HEAD','HEAL','TEAL','TELL','TALL','TAIL','GAME','GATE','CATE','CADE','CODE','SAME','CAME','CANE','CONE']); }
  key(e){ if(this.over||this.paused) return; if(/^[a-zA-Z]$/.test(e.key)&&this.keyBuffer.length<4){ this.keyBuffer+=e.key.toUpperCase(); AudioEngine.play('click'); } if(e.key==='Backspace')this.keyBuffer=this.keyBuffer.slice(0,-1); if(e.key==='Enter')this.submit(this.keyBuffer); }
  diff(a,b){ let n=0; for(let i=0;i<a.length;i++) if(a[i]!==b[i]) n++; return n; }
  submit(word){ word=word.toUpperCase(); if(word.length!==4||!this.dictionary.has(word)||this.diff(word,this.current)!==1||this.path.includes(word)){ this.lives--; this.keyBuffer=''; AudioEngine.play('failure'); if(this.lives<=0)this.gameOver('Word chain broke'); return; } this.current=word; this.path.push(word); this.keyBuffer=''; this.score+=100; AudioEngine.play('success'); if(word===this.target){ this.score+=500; this.pi++; if(this.pi>=this.puzzles.length){ this.rewardWin('All word ladders solved','Lexical Perfect Badge',1200); return; } this.current=this.puzzles[this.pi][0]; this.target=this.puzzles[this.pi][1]; this.path=[this.current]; AudioEngine.play('powerup'); } }
  pick(e){ const p=this.pointer(e); const opts=this.puzzles[this.pi][2]; for(let i=0;i<opts.length;i++){ const x=96+i*150,y=460; if(p.x>x&&p.x<x+125&&p.y>y&&p.y<505) this.submit(opts[i]); } }
  update(){ this.updateHUD({Puzzle:`${this.pi+1}/3`,Current:this.current,Target:this.target,Input:this.keyBuffer||'type/click',Goal:'Reach target word',Reward:'Lexical Perfect Badge'}); }
  draw(){ const c=this.ctx; c.fillStyle='#061020'; c.fillRect(0,0,800,600); c.fillStyle='#cbd7ff'; c.font='bold 28px system-ui'; c.fillText(this.current+'  →  '+this.target,245,80); c.font='18px system-ui'; c.fillText('Change exactly one letter each step. Type a valid word and press Enter, or click a suggested step.',72,126);
    c.fillStyle='#1e2a44'; c.fillRect(250,160,300,56); c.fillStyle='#fff'; c.font='bold 34px monospace'; c.textAlign='center'; c.fillText(this.keyBuffer.padEnd(4,'_'),400,199); c.textAlign='left';
    c.fillStyle='#9fb3ff'; c.font='18px system-ui'; c.fillText('Chain:',92,260); for(let i=0;i<this.path.length;i++){ c.fillStyle='#18e0ff'; c.fillRect(92+i*110,285,94,40); c.fillStyle='#061020'; c.font='bold 20px monospace'; c.fillText(this.path[i],112+i*110,312); }
    c.fillStyle='#ffd166'; c.fillText('Suggested playable path buttons:',92,438); const opts=this.puzzles[this.pi][2]; for(let i=0;i<opts.length;i++){ const x=96+i*150,y=460; c.fillStyle='#24314a'; c.fillRect(x,y,125,45); c.strokeStyle='#18e0ff'; c.strokeRect(x,y,125,45); c.fillStyle='#fff'; c.font='bold 21px monospace'; c.fillText(opts[i],x+35,y+29); }
  }
}
window.currentGame=new LexicalDrift(); window.currentGame.start();
