class MahjongTiles extends BaseGame{
  rewardWin(message, reward, bonus=250){ if(this.over) return; this.score += bonus; StorageManager.saveAchievement(this.gameId, 'reward-'+reward.toLowerCase().replace(/[^a-z0-9]+/g,'-'), 'Reward: '+reward); this.win(message + ' — Reward: ' + reward); }
  reset(){this.symbols=['🀄','🌸','🐉','🎋','🪙','🔥','💧','⭐'];let rows=[['🀄','🌸','🐉','🎋','🎋','🐉','🌸','🀄'],['🪙','🔥','💧','⭐','⭐','💧','🔥','🪙'],['🀄','🌸','🐉','🎋','🎋','🐉','🌸','🀄'],['🪙','🔥','💧','⭐','⭐','💧','🔥','🪙']];this.tiles=[];for(let y=0;y<4;y++)for(let x=0;x<8;x++)this.tiles.push({x,y,z:0,s:rows[y][x],gone:false});this.sel=null;this.cell=70;this.off={x:120,y:120};this.score=0;if(!this.boundControls){this.boundControls=true;this.canvas.addEventListener('pointerdown',e=>this.pick(e));}}
  screen(t){return {x:this.off.x+t.x*this.cell+t.z*12,y:this.off.y+t.y*this.cell-t.z*16,w:62,h:50};}
  free(t){if(t.gone)return false;let left=this.tiles.some(o=>!o.gone&&o.z===t.z&&o.y===t.y&&o.x===t.x-1),right=this.tiles.some(o=>!o.gone&&o.z===t.z&&o.y===t.y&&o.x===t.x+1);return !(left&&right);}
  pick(e){let p=this.pointer(e);let candidates=this.tiles.filter(t=>!t.gone).sort((a,b)=>b.z-a.z);let t=candidates.find(t=>{let r=this.screen(t);return p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h;});if(!t||!this.free(t)){AudioEngine.play('failure');return;}if(!this.sel){this.sel=t;AudioEngine.play('click');return;}if(this.sel!==t&&this.sel.s===t.s){this.sel.gone=t.gone=true;this.score+=100;this.sel=null;AudioEngine.play('success');}else{this.sel=t;AudioEngine.play('click');}}
  update(){if(this.tiles.every(t=>t.gone)){this.rewardWin('Tiles Cleared','Tile Master Jade',800);return;}let moves=0;let free=this.tiles.filter(t=>this.free(t));for(let i=0;i<free.length;i++)for(let j=i+1;j<free.length;j++)if(free[i].s===free[j].s)moves++;if(!moves&&!this.tiles.every(t=>t.gone)){this.gameOver('No Free Matches');return;}this.updateHUD({Tiles:this.tiles.filter(t=>!t.gone).length,Moves:moves,Goal:'Clear all pairs',Reward:'Tile Master Jade'});}
  draw(){let c=this.ctx;c.font='30px serif';c.textAlign='center';c.textBaseline='middle';for(const t of this.tiles.filter(t=>!t.gone).sort((a,b)=>a.z-b.z)){let r=this.screen(t);c.fillStyle=this.sel===t?'#ffd166':this.free(t)?'#f8fafc':'#94a3b8';c.fillRect(r.x,r.y,r.w,r.h);c.strokeStyle='#334155';c.strokeRect(r.x,r.y,r.w,r.h);c.fillStyle='#111827';c.fillText(t.s,r.x+r.w/2,r.y+r.h/2);}}
}
document.addEventListener('DOMContentLoaded',()=>{window.currentGame=new MahjongTiles('mahjong-tiles','Mahjong Tiles');window.currentGame.start();});
