class ArcheryMaster extends BaseGame{
  rewardWin(message, reward, bonus=250){ if(this.over) return; this.score += bonus; StorageManager.saveAchievement(this.gameId, 'reward-'+reward.toLowerCase().replace(/[^a-z0-9]+/g,'-'), 'Reward: '+reward); this.win(message + ' — Reward: ' + reward); }

 reset(){this.aim=300;this.target={x:650,y:300,dir:1};this.arrow=null;this.shots=10;this.score=0;}
 handleAction(a){if(a==='action'&&!this.arrow&&this.shots>0){this.arrow={x:90,y:this.aim,vx:620};this.shots--;AudioEngine.play('shoot');}}
 update(dt){if(this.input.isPressed('up'))this.aim-=260*dt;if(this.input.isPressed('down'))this.aim+=260*dt;this.aim=Utils.clamp(this.aim,80,520);this.target.y+=this.target.dir*(110+this.score*.02)*dt;if(this.target.y<115||this.target.y>485)this.target.dir*=-1;if(this.arrow){this.arrow.x+=this.arrow.vx*dt;if(this.arrow.x>this.target.x){let d=Math.abs(this.arrow.y-this.target.y),pts=d<18?100:d<42?60:d<72?25:0;this.score+=pts;AudioEngine.play(pts?'success':'failure');this.arrow=null;}if(this.arrow&&this.arrow.x>820)this.arrow=null;}if(this.shots<=0&&!this.arrow){this.score>=450?this.rewardWin('Bullseye Set', 'Bullseye Medal'):this.gameOver('Quiver Empty');}this.updateHUD({Shots:this.shots,Goal:'450 pts',Aim:Math.floor(this.aim),Reward:'Bullseye Medal'});}
 draw(){let c=this.ctx;c.strokeStyle='#a16207';c.lineWidth=5;c.beginPath();c.arc(90,this.aim,45,-1.1,1.1);c.stroke();c.strokeStyle='#ffd166';c.beginPath();c.moveTo(92,this.aim);c.lineTo(140,this.aim);c.stroke();c.fillStyle='#fff';c.beginPath();c.arc(this.target.x,this.target.y,75,0,7);c.fill();c.fillStyle='#ff4d6d';c.beginPath();c.arc(this.target.x,this.target.y,48,0,7);c.fill();c.fillStyle='#ffd166';c.beginPath();c.arc(this.target.x,this.target.y,18,0,7);c.fill();if(this.arrow){c.strokeStyle='#fff';c.beginPath();c.moveTo(this.arrow.x-35,this.arrow.y);c.lineTo(this.arrow.x+10,this.arrow.y);c.stroke();}}
}
document.addEventListener('DOMContentLoaded',()=>{window.currentGame=new ArcheryMaster('archery-master','Archery Master');window.currentGame.start();});
