class RoguelikeDungeonGame extends BaseGame {
  constructor(){ super('roguelike-dungeon','Roguelike Dungeon Crawler'); this.cols=28; this.rows=20; this.cell=26; this.ox=36; this.oy=40; }
  reset(){ this.rng=Utils.createRng(Date.now()%999999); this.map=Array.from({length:this.rows},()=>Array(this.cols).fill(1)); this.rooms=[]; for(let i=0;i<9;i++){ const w=4+Math.floor(this.rng()*5), h=3+Math.floor(this.rng()*4), x=1+Math.floor(this.rng()*(this.cols-w-2)), y=1+Math.floor(this.rng()*(this.rows-h-2)); const room={x,y,w,h,cx:Math.floor(x+w/2),cy:Math.floor(y+h/2)}; this.rooms.push(room); for(let yy=y;yy<y+h;yy++) for(let xx=x;xx<x+w;xx++) this.map[yy][xx]=0; if(i){ const prev=this.rooms[i-1]; for(let xx=Math.min(prev.cx,room.cx);xx<=Math.max(prev.cx,room.cx);xx++) this.map[prev.cy][xx]=0; for(let yy=Math.min(prev.cy,room.cy);yy<=Math.max(prev.cy,room.cy);yy++) this.map[yy][room.cx]=0; } } const start=this.rooms[0]; this.player={x:start.cx,y:start.cy,hp:14,max:14}; this.enemies=[]; this.loot=[]; for(const r of this.rooms.slice(1)){ if(this.rng()<.8) this.enemies.push({x:r.cx,y:r.cy,hp:3+this.level,state:'idle'}); if(this.rng()<.65) this.loot.push({x:r.x+1,y:r.y+1,type:'gem'}); } const end=this.rooms.at(-1); this.exit={x:end.cx,y:end.cy}; }
  handleDirection(d){ if(this.over||this.paused) return; const map={left:[-1,0],right:[1,0],up:[0,-1],down:[0,1]}; const [dx,dy]=map[d]||[0,0]; this.playerTurn(dx,dy); }
  playerTurn(dx,dy){ const nx=this.player.x+dx, ny=this.player.y+dy; const enemy=this.enemies.find(e=>e.x===nx&&e.y===ny); if(enemy){ enemy.hp-=2; this.score+=10; AudioEngine.play('shoot'); if(enemy.hp<=0){ this.enemies.splice(this.enemies.indexOf(enemy),1); this.score+=30; } } else if(this.map[ny]?.[nx]===0){ this.player.x=nx; this.player.y=ny; } const loot=this.loot.find(l=>l.x===this.player.x&&l.y===this.player.y); if(loot){ this.loot.splice(this.loot.indexOf(loot),1); this.score+=50; this.player.hp=Math.min(this.player.max,this.player.hp+2); AudioEngine.play('coin'); } if(this.player.x===this.exit.x&&this.player.y===this.exit.y) this.win('Dungeon escaped'); this.enemyTurn(); this.updateHUD({HP:this.player.hp, Enemies:this.enemies.length}); }
  enemyTurn(){ for(const e of this.enemies){ const dist=Math.abs(e.x-this.player.x)+Math.abs(e.y-this.player.y); if(dist===1){ this.player.hp--; AudioEngine.play('failure'); if(this.player.hp<=0) this.gameOver('The dungeon defeated you'); continue; } if(dist<7){ e.state='chase'; const opts=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:e.x+dx,y:e.y+dy})).filter(p=>this.map[p.y]?.[p.x]===0&&!this.enemies.some(o=>o!==e&&o.x===p.x&&o.y===p.y)); opts.sort((a,b)=>Math.abs(a.x-this.player.x)+Math.abs(a.y-this.player.y)-Math.abs(b.x-this.player.x)-Math.abs(b.y-this.player.y)); if(opts[0] && !(opts[0].x===this.player.x&&opts[0].y===this.player.y)){ e.x=opts[0].x; e.y=opts[0].y; } } } }
  update(){ this.updateHUD({HP:this.player.hp, Enemies:this.enemies.length}); }
  visible(x,y){ return Math.hypot(x-this.player.x,y-this.player.y)<7; }
  draw(){ const c=this.ctx; for(let y=0;y<this.rows;y++) for(let x=0;x<this.cols;x++){ c.fillStyle=this.visible(x,y)?(this.map[y][x]?'#111827':'#243b5a'):'#030712'; c.fillRect(this.ox+x*this.cell,this.oy+y*this.cell,this.cell-1,this.cell-1); } c.fillStyle='#ffd166'; c.fillRect(this.ox+this.exit.x*this.cell+5,this.oy+this.exit.y*this.cell+5,16,16); c.fillStyle='#36e28f'; for(const l of this.loot) if(this.visible(l.x,l.y)) c.fillRect(this.ox+l.x*this.cell+8,this.oy+l.y*this.cell+8,10,10); c.fillStyle='#ff4d6d'; for(const e of this.enemies) if(this.visible(e.x,e.y)) c.fillRect(this.ox+e.x*this.cell+4,this.oy+e.y*this.cell+4,18,18); c.fillStyle='#18e0ff'; c.fillRect(this.ox+this.player.x*this.cell+4,this.oy+this.player.y*this.cell+4,18,18); }
}
window.currentGame = new RoguelikeDungeonGame(); window.addEventListener('DOMContentLoaded', () => currentGame.start());
