class BowlingStrike extends BaseGame{
  rewardWin(message, reward, bonus=250){ if(this.over) return; this.score += bonus; StorageManager.saveAchievement(this.gameId, 'reward-'+reward.toLowerCase().replace(/[^a-z0-9]+/g,'-'), 'Reward: '+reward); this.win(message + ' — Reward: ' + reward); }

 reset(){this.ball={x:400,y:535,vx:0,vy:0,r:16,roll:false};this.aim=0;this.rolls=2;this.pins=[];for(let row=0;row<4;row++)for(let i=0;i<=row;i++)this.pins.push({x:400+(i-row/2)*38,y:135+row*34,hit:false,vx:0,vy:0});this.score=0;}
 handleAction(a){if(a==='action'&&!this.ball.roll&&this.rolls>0){this.ball.vx=this.aim*260;this.ball.vy=-520;this.ball.roll=true;this.rolls--;AudioEngine.play('shoot');}}
 update(dt){if(this.input.isPressed('left'))this.aim-=dt;if(this.input.isPressed('right'))this.aim+=dt;this.aim=Utils.clamp(this.aim,-1,1);let b=this.ball;if(b.roll){b.x+=b.vx*dt;b.y+=b.vy*dt;b.vy*=.995;if(b.x<250||b.x>550)b.vx*=-.8;for(const p of this.pins)if(!p.hit&&Math.hypot(b.x-p.x,b.y-p.y)<b.r+12){p.hit=true;p.vx=(p.x-b.x)*3;p.vy=-130;this.score+=10;AudioEngine.play('coin');}if(b.y<50||Math.abs(b.vy)<80){b.roll=false;b.x=400;b.y=535;b.vx=b.vy=0;}}for(const p of this.pins)if(p.hit){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=380*dt;}if(this.score>=100)this.rewardWin('Strike!', 'Perfect Frame Patch');else if(this.rolls<=0&&!b.roll)this.gameOver('Frame Finished');this.updateHUD({Rolls:this.rolls,Pins:this.score/10+'/10',Goal:'10 pins',Reward:'Perfect Frame Patch'});}
 draw(){let c=this.ctx;c.fillStyle='#8b5a2b';c.fillRect(230,40,340,540);c.strokeStyle='#fff';c.strokeRect(250,40,300,540);c.strokeStyle='#ffd166';c.beginPath();c.moveTo(400,535);c.lineTo(400+this.aim*120,450);c.stroke();c.fillStyle='#7c5cff';c.beginPath();c.arc(this.ball.x,this.ball.y,this.ball.r,0,7);c.fill();for(const p of this.pins){if(p.hit)c.globalAlpha=.4;c.fillStyle='#fff';c.beginPath();c.roundRect?c.roundRect(p.x-10,p.y-18,20,36,8):c.rect(p.x-10,p.y-18,20,36);c.fill();c.globalAlpha=1;}}
}
document.addEventListener('DOMContentLoaded',()=>{window.currentGame=new BowlingStrike('bowling-strike','Bowling Strike');window.currentGame.start();});
