class ChessLite extends BaseGame{
  rewardWin(message, reward, bonus=250){ if(this.over) return; this.score += bonus; StorageManager.saveAchievement(this.gameId, 'reward-'+reward.toLowerCase().replace(/[^a-z0-9]+/g,'-'), 'Reward: '+reward); this.win(message + ' — Reward: ' + reward); }

 reset(){this.n=6;this.cell=72;this.off={x:184,y:74};this.knight={x:1,y:4};this.crown={x:4,y:1};this.blocks=[{x:2,y:2},{x:3,y:3},{x:1,y:1}];this.turn='player';this.moves=0;this.moveLimit=16;this.score=600;if(!this.boundControls){this.boundControls=true;this.canvas.addEventListener('pointerdown',e=>this.pick(e));}}
 pick(e){if(this.turn!=='player'||this.over)return;let p=this.pointer(e),x=Math.floor((p.x-this.off.x)/this.cell),y=Math.floor((p.y-this.off.y)/this.cell);let ok=this.legal(this.knight.x,this.knight.y).some(m=>m.x===x&&m.y===y);if(ok){this.knight={x,y};this.moves++;AudioEngine.play('click');if(x===this.crown.x&&y===this.crown.y){this.score=Math.max(100,700-this.moves*50);this.rewardWin('Crown Captured', 'Crown Capture Award');return;}if(this.moves>=this.moveLimit){this.gameOver('Crown Escaped');return;}this.turn='ai';setTimeout(()=>this.ai(),180);}}
 blocked(x,y){return x<0||y<0||x>=this.n||y>=this.n||this.blocks.some(b=>b.x===x&&b.y===y);}
 legal(x,y){return [[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]].map(d=>({x:x+d[0],y:y+d[1]})).filter(m=>!this.blocked(m.x,m.y));}
 ai(){let dirs=[[1,0],[-1,0],[0,1],[0,-1]].map(d=>({x:this.crown.x+d[0],y:this.crown.y+d[1]})).filter(m=>!this.blocked(m.x,m.y)&&!(m.x===this.knight.x&&m.y===this.knight.y));dirs.sort((a,b)=>Math.abs(b.x-this.knight.x)+Math.abs(b.y-this.knight.y)-Math.abs(a.x-this.knight.x)-Math.abs(a.y-this.knight.y));if(dirs[0])this.crown=dirs[0];this.turn='player';}
 update(){this.updateHUD({Turn:this.turn,Moves:this.moves+'/'+this.moveLimit,Reward:'Crown Capture Award'});}
 draw(){let c=this.ctx;c.font='42px serif';c.textAlign='center';c.textBaseline='middle';for(let y=0;y<this.n;y++)for(let x=0;x<this.n;x++){c.fillStyle=(x+y)%2?'#243b63':'#e0e7ff';c.fillRect(this.off.x+x*this.cell,this.off.y+y*this.cell,this.cell,this.cell);}c.fillStyle='#111827';for(const b of this.blocks)c.fillRect(this.off.x+b.x*this.cell+8,this.off.y+b.y*this.cell+8,this.cell-16,this.cell-16);c.fillText('♞',this.off.x+this.knight.x*this.cell+36,this.off.y+this.knight.y*this.cell+38);c.fillText('♛',this.off.x+this.crown.x*this.cell+36,this.off.y+this.crown.y*this.cell+38);}
}
document.addEventListener('DOMContentLoaded',()=>{window.currentGame=new ChessLite('chess-lite','Chess Lite');window.currentGame.start();});
