class StealthEscapeGame extends BaseGame {
  constructor(){ super('stealth-escape','Stealth Escape'); }
  reset(){ this.player={x:65,y:520,r:12,hidden:false}; this.goal={x:725,y:55,w:50,h:50}; this.walls=[{x:145,y:95,w:45,h:390},{x:300,y:0,w:45,h:340},{x:455,y:250,w:45,h:350},{x:610,y:80,w:45,h:390}]; this.guards=[this.guard([[230,70],[230,520]]), this.guard([[390,520],[390,80]]), this.guard([[570,80],[720,80],[720,420],[570,420]])]; this.alert=0; }
  guard(route){ return {route:route.map(([x,y])=>({x,y})), i:0, x:route[0][0], y:route[0][1], angle:0, state:'patrol', lastSeen:null, wait:0}; }
  blocked(x,y){ return this.walls.some(w=>Utils.rectsOverlap({x:x-10,y:y-10,w:20,h:20},w)); }
  canSee(g){ const dx=this.player.x-g.x, dy=this.player.y-g.y, dist=Math.hypot(dx,dy); if(dist>150||this.player.hidden) return false; const angle=Math.atan2(dy,dx); let diff=Math.atan2(Math.sin(angle-g.angle),Math.cos(angle-g.angle)); if(Math.abs(diff)>.55) return false; for(const w of this.walls){ const steps=12; for(let i=1;i<steps;i++){ const x=g.x+dx*i/steps,y=g.y+dy*i/steps; if(x>w.x&&x<w.x+w.w&&y>w.y&&y<w.y+w.h) return false; } } return true; }
  handleAction(){ this.player.hidden=!this.player.hidden; AudioEngine.play('click'); }
  update(dt){ const speed=this.player.hidden?80:150; let dx=0,dy=0; if(this.input.isPressed('left'))dx--; if(this.input.isPressed('right'))dx++; if(this.input.isPressed('up'))dy--; if(this.input.isPressed('down'))dy++; const len=Math.hypot(dx,dy)||1; const nx=this.player.x+dx/len*speed*dt, ny=this.player.y+dy/len*speed*dt; if(!this.blocked(nx,ny)){ this.player.x=Utils.clamp(nx,15,785); this.player.y=Utils.clamp(ny,15,585); }
    for(const g of this.guards){ if(this.canSee(g)){ g.state='chase'; g.lastSeen={x:this.player.x,y:this.player.y}; this.alert+=dt*35; } else if(g.state==='chase' && g.lastSeen && Math.hypot(g.x-g.lastSeen.x,g.y-g.lastSeen.y)<8){ g.state='search'; g.wait=1.2; } else if(g.state==='search'){ g.wait-=dt; if(g.wait<=0) g.state='patrol'; }
      let target; if(g.state==='chase'&&g.lastSeen) target=g.lastSeen; else { target=g.route[g.i]; if(Math.hypot(g.x-target.x,g.y-target.y)<6) g.i=(g.i+1)%g.route.length; target=g.route[g.i]; } const vx=target.x-g.x, vy=target.y-g.y, d=Math.hypot(vx,vy)||1; g.angle=Math.atan2(vy,vx); g.x+=vx/d*(g.state==='chase'?125:70)*dt; g.y+=vy/d*(g.state==='chase'?125:70)*dt; if(Math.hypot(g.x-this.player.x,g.y-this.player.y)<18&&!this.player.hidden) this.gameOver('Caught by a guard'); }
    this.alert=Math.max(0,this.alert-dt*8); if(this.alert>100) this.gameOver('Alarm fully raised'); if(Utils.rectsOverlap({x:this.player.x-10,y:this.player.y-10,w:20,h:20},this.goal)) this.win('Escaped undetected'); this.score=Math.max(0,Math.floor(1000-this.elapsed*8-this.alert*3)); this.updateHUD({Alert:Math.floor(this.alert), Hidden:this.player.hidden?'Yes':'No'}); }
  draw(){ const c=this.ctx; c.fillStyle='#0e1729'; c.fillRect(0,0,800,600); c.fillStyle='#36e28f'; c.fillRect(this.goal.x,this.goal.y,this.goal.w,this.goal.h); c.fillStyle='#334155'; this.walls.forEach(w=>c.fillRect(w.x,w.y,w.w,w.h)); for(const g of this.guards){ c.fillStyle=g.state==='chase'?'rgba(255,77,109,.28)':'rgba(255,209,102,.18)'; c.beginPath(); c.moveTo(g.x,g.y); c.arc(g.x,g.y,150,g.angle-.55,g.angle+.55); c.closePath(); c.fill(); c.fillStyle=g.state==='chase'?'#ff4d6d':'#ffd166'; c.beginPath(); c.arc(g.x,g.y,13,0,Math.PI*2); c.fill(); } c.fillStyle=this.player.hidden?'#7c5cff':'#18e0ff'; c.beginPath(); c.arc(this.player.x,this.player.y,this.player.r,0,Math.PI*2); c.fill(); }
}
window.currentGame = new StealthEscapeGame(); window.addEventListener('DOMContentLoaded', () => currentGame.start());
