
class NeonStation extends BaseGame {
  constructor(){ super('neon-station','Neon Station'); this.keys={}; this.pointerPos={x:400,y:300}; this.canvas.addEventListener('pointermove',e=>{this.pointerPos=this.pointer(e);}); this.canvas.addEventListener('pointerdown',e=>{this.pointerPos=this.pointer(e); this.fire(false);}); }
  reset(){ this.player={x:400,y:300,r:14,hp:100,ammo:90,shotgun:8,shield:25}; this.wave=1; this.level=1; this.score=0; this.lives=3; this.enemies=[]; this.projectiles=[]; this.bullets=[]; this.pickups=[]; this.spawnTimer=0; this.waveClear=0; this.fireCd=0; this.shotgunCd=0; this.screenShake=0; this.bossSpawned=false; this.spawnWave(); }
  spawnWave(){ this.enemies=[]; this.projectiles=[]; this.spawnTimer=0; this.bossSpawned=false; const count=5+this.wave*2; for(let i=0;i<count;i++){ this.spawnEnemy(i%3===0?'sentinel':i%4===0?'phantom':'drone'); } if(this.wave===10){ this.spawnEnemy('boss'); this.bossSpawned=true; } }
  spawnEnemy(type){ const edge=Math.floor(Math.random()*4); const x=edge===0?-40:edge===1?840:Math.random()*800; const y=edge===2?-40:edge===3?640:Math.random()*600; const hp={drone:35,sentinel:70,phantom:48,boss:520}[type]; this.enemies.push({x,y,type,hp,max:hp,cd:1+Math.random(),phase:Math.random()*6,visible:type!=='phantom'}); }
  update(dt){
    this.fireCd=Math.max(0,this.fireCd-dt); this.shotgunCd=Math.max(0,this.shotgunCd-dt); this.screenShake=Math.max(0,this.screenShake-dt);
    let vx=0,vy=0, sp=this.input.isPressed('secondary')?125:210; if(this.input.isPressed('left'))vx-=1; if(this.input.isPressed('right'))vx+=1; if(this.input.isPressed('up'))vy-=1; if(this.input.isPressed('down'))vy+=1; const l=Math.hypot(vx,vy)||1; this.player.x=Utils.clamp(this.player.x+vx/l*sp*dt,30,770); this.player.y=Utils.clamp(this.player.y+vy/l*sp*dt,30,570);
    if(this.input.isPressed('action')) this.fire(false); if(this.input.isPressed('secondary')&&this.input.isPressed('action')) this.fire(true);
    for(const b of this.bullets){ b.x+=b.vx*dt; b.y+=b.vy*dt; b.life-=dt; }
    for(const p of this.projectiles){ p.x+=p.vx*dt; p.y+=p.vy*dt; p.life-=dt; if(Math.hypot(p.x-this.player.x,p.y-this.player.y)<this.player.r+6){ p.life=0; let dmg=p.dmg; if(this.player.shield>0){ const s=Math.min(this.player.shield,dmg*.65); this.player.shield-=s; dmg-=s; } this.player.hp-=dmg; this.screenShake=.12; AudioEngine.play('warning'); if(this.player.hp<=0){ this.lives=0; this.gameOver('Station overrun — operator eliminated'); } } }
    this.bullets=this.bullets.filter(b=>b.life>0&&b.x>-80&&b.x<880&&b.y>-80&&b.y<680); this.projectiles=this.projectiles.filter(p=>p.life>0);
    for(const e of this.enemies){ if(e.hp<=0) continue; const dx=this.player.x-e.x,dy=this.player.y-e.y,d=Math.hypot(dx,dy)||1; e.phase+=dt; if(e.type==='phantom') e.visible=d<170||e.hp<e.max; let speed={drone:105,sentinel:48,phantom:135,boss:35}[e.type]; if(e.type==='sentinel'&&d<210) speed=10; if(e.type==='boss'&&d<260) speed=5; e.x+=dx/d*speed*dt; e.y+=dy/d*speed*dt; e.cd-=dt;
      if((e.type==='drone'||e.type==='phantom')&&d<e.max/3+20){ this.player.hp-=18*dt; this.screenShake=.08; }
      if((e.type==='sentinel'||e.type==='boss')&&e.cd<=0&&d<620){ e.cd=e.type==='boss'?.55:1.25; const n=e.type==='boss'?3:1; for(let k=0;k<n;k++){ const a=Math.atan2(dy,dx)+(k-(n-1)/2)*.22; this.projectiles.push({x:e.x,y:e.y,vx:Math.cos(a)*180,vy:Math.sin(a)*180,life:4,dmg:e.type==='boss'?12:9}); } AudioEngine.play('shoot'); }
    }
    for(const b of this.bullets){ for(const e of this.enemies){ if(e.hp<=0) continue; if(Math.hypot(b.x-e.x,b.y-e.y)<(e.type==='boss'?38:20)){ e.hp-=b.dmg; b.life=0; this.particles.push(...Utils.makeParticles(e.x,e.y,8,'#ff4d6d')); if(e.hp<=0){ this.score+=e.type==='boss'?3000:e.type==='sentinel'?420:260; if(Math.random()<.28) this.pickups.push({x:e.x,y:e.y,type:Math.random()<.5?'ammo':'health'}); AudioEngine.play('explosion'); } else AudioEngine.play('success'); } } }
    for(const p of this.pickups){ if(!p.taken&&Math.hypot(p.x-this.player.x,p.y-this.player.y)<28){ p.taken=true; if(p.type==='ammo') this.player.ammo+=35; else this.player.hp=Math.min(100,this.player.hp+25); AudioEngine.play('powerup'); } }
    this.pickups=this.pickups.filter(p=>!p.taken);
    const alive=this.enemies.filter(e=>e.hp>0).length; if(alive===0){ this.waveClear+=dt; if(this.wave>=10){ this.score+=5000+Math.floor(this.player.hp*20); StorageManager.saveAchievement(this.gameId,'neon-station-victory','Reward: Neon Station Wave-10 Emblem'); this.win('Wave 10 cleared — Reward: Neon Station Wave-10 Emblem'); } else if(this.waveClear>1.2){ this.wave++; this.level=this.wave; this.waveClear=0; this.player.shield=Math.min(50,this.player.shield+15); this.player.ammo+=20; this.spawnWave(); AudioEngine.play('reward'); } } else this.waveClear=0;
    this.updateHUD({HP:Math.max(0,Math.floor(this.player.hp)),Shield:Math.floor(this.player.shield),Ammo:this.player.ammo,Shotgun:this.player.shotgun,Wave:`${this.wave}/10`,Enemies:alive,Goal:'Survive 10 waves',Reward:'Neon Station Emblem'});
  }
  handleAction(a){ if(a==='action') this.fire(false); if(a==='secondary') this.fire(true); }
  fire(shotgun=false){ if(this.over||this.paused) return; const dx=this.pointerPos.x-this.player.x,dy=this.pointerPos.y-this.player.y; const base=Math.atan2(dy,dx); if(shotgun){ if(this.shotgunCd>0||this.player.shotgun<=0) return; this.shotgunCd=.85; this.player.shotgun--; for(let i=-3;i<=3;i++) this.spawnBullet(base+i*.11,18); AudioEngine.play('explosion'); } else { if(this.fireCd>0||this.player.ammo<=0) return; this.fireCd=.09; this.player.ammo--; this.spawnBullet(base,24); AudioEngine.play('shoot'); } }
  spawnBullet(a,dmg){ this.bullets.push({x:this.player.x+Math.cos(a)*18,y:this.player.y+Math.sin(a)*18,vx:Math.cos(a)*520,vy:Math.sin(a)*520,life:.85,dmg}); }
  drawGrid(c){ c.strokeStyle='rgba(24,224,255,.12)'; c.lineWidth=1; for(let x=-100;x<900;x+=40){ c.beginPath(); c.moveTo(x+Math.sin(this.elapsed*2+x)*4,0); c.lineTo(x+Math.sin(this.elapsed*2+x)*4,600); c.stroke(); } for(let y=20;y<600;y+=40){ c.beginPath(); c.moveTo(0,y+Math.cos(this.elapsed*2+y)*4); c.lineTo(800,y+Math.cos(this.elapsed*2+y)*4); c.stroke(); } }
  draw(){ const c=this.ctx; c.save(); if(this.screenShake)c.translate((Math.random()-.5)*12,(Math.random()-.5)*12); const bg=c.createRadialGradient(400,300,30,400,300,520); bg.addColorStop(0,'#111a3a'); bg.addColorStop(1,'#020611'); c.fillStyle=bg; c.fillRect(-20,-20,840,640); this.drawGrid(c); c.strokeStyle='rgba(255,255,255,.2)'; c.lineWidth=4; c.strokeRect(18,18,764,564);
    for(const p of this.pickups){ c.shadowBlur=20; c.shadowColor=p.type==='ammo'?'#18e0ff':'#36e28f'; c.fillStyle=p.type==='ammo'?'#18e0ff':'#36e28f'; c.beginPath(); c.arc(p.x,p.y,12,0,Math.PI*2); c.fill(); c.shadowBlur=0; }
    for(const b of this.bullets){ c.strokeStyle='#9ff'; c.lineWidth=3; c.beginPath(); c.moveTo(b.x-b.vx*.025,b.y-b.vy*.025); c.lineTo(b.x,b.y); c.stroke(); }
    for(const p of this.projectiles){ c.shadowBlur=14; c.shadowColor='#ff4d6d'; c.fillStyle='#ff4d6d'; c.beginPath(); c.arc(p.x,p.y,6,0,Math.PI*2); c.fill(); c.shadowBlur=0; }
    for(const e of this.enemies){ if(e.hp<=0) continue; const alpha=e.visible?1:.16; c.globalAlpha=alpha; c.shadowBlur=22; c.shadowColor=e.type==='phantom'?'#b18cff':e.type==='boss'?'#ffb703':'#ff4d6d'; c.fillStyle=e.type==='drone'?'#ff4d6d':e.type==='sentinel'?'#ffb703':e.type==='phantom'?'#b18cff':'#ff006e'; const r=e.type==='boss'?42:20; c.save(); c.translate(e.x,e.y); c.rotate(e.phase); c.beginPath(); for(let i=0;i<6;i++){ const a=i*Math.PI*2/6; c.lineTo(Math.cos(a)*r,Math.sin(a)*r); } c.closePath(); c.fill(); c.shadowBlur=0; c.fillStyle='#020611'; c.fillRect(-r,-r-14,r*2,5); c.fillStyle='#36e28f'; c.fillRect(-r,-r-14,r*2*(e.hp/e.max),5); c.restore(); c.globalAlpha=1; }
    c.shadowBlur=18; c.shadowColor='#18e0ff'; c.fillStyle='#18e0ff'; c.beginPath(); c.arc(this.player.x,this.player.y,this.player.r,0,Math.PI*2); c.fill(); c.strokeStyle='#fff'; c.beginPath(); c.moveTo(this.player.x,this.player.y); c.lineTo(this.pointerPos.x,this.pointerPos.y); c.stroke(); c.shadowBlur=0; c.strokeStyle='#fff'; c.beginPath(); c.arc(this.pointerPos.x,this.pointerPos.y,9,0,Math.PI*2); c.moveTo(this.pointerPos.x-15,this.pointerPos.y); c.lineTo(this.pointerPos.x+15,this.pointerPos.y); c.moveTo(this.pointerPos.x,this.pointerPos.y-15); c.lineTo(this.pointerPos.x,this.pointerPos.y+15); c.stroke(); c.restore(); }
}
window.currentGame=new NeonStation(); window.currentGame.start();
