class CheckersClassic extends BaseGame{
  rewardWin(message, reward, bonus=250){ if(this.over) return; this.score += bonus; StorageManager.saveAchievement(this.gameId, 'reward-'+reward.toLowerCase().replace(/[^a-z0-9]+/g,'-'), 'Reward: '+reward); this.win(message + ' — Reward: ' + reward); }

 reset(){this.n=8;this.cell=58;this.off={x:168,y:60};this.board=Array.from({length:8},()=>Array(8).fill(null));for(let y=0;y<3;y++)for(let x=0;x<8;x++)if((x+y)%2)this.board[y][x]='b';for(let y=5;y<8;y++)for(let x=0;x<8;x++)if((x+y)%2)this.board[y][x]='r';this.sel=null;this.turn='r';this.score=0;if(!this.boundControls){this.boundControls=true;this.canvas.addEventListener('pointerdown',e=>this.pick(e));}}
 moves(x,y){let p=this.board[y][x],dir=p==='r'?-1:1,ms=[];for(const dx of [-1,1]){let nx=x+dx,ny=y+dir;if(this.board[ny]?.[nx]===null)ms.push({x:nx,y:ny});let jx=x+dx*2,jy=y+dir*2;if(this.board[ny]?.[nx]&&this.board[ny][nx]!==p&&this.board[jy]?.[jx]===null)ms.push({x:jx,y:jy,cx:nx,cy:ny});}return ms;}
 pick(e){if(this.turn!=='r'||this.over)return;let p=this.pointer(e),x=Math.floor((p.x-this.off.x)/this.cell),y=Math.floor((p.y-this.off.y)/this.cell);if(this.board[y]?.[x]==='r'){this.sel={x,y};return;}if(this.sel){let m=this.moves(this.sel.x,this.sel.y).find(m=>m.x===x&&m.y===y);if(m){this.board[y][x]='r';this.board[this.sel.y][this.sel.x]=null;if(m.cx!=null){this.board[m.cy][m.cx]=null;this.score+=50;AudioEngine.play('success');}else AudioEngine.play('click');this.sel=null;this.turn='b';setTimeout(()=>this.ai(),200);}}}
 ai(){let all=[];for(let y=0;y<8;y++)for(let x=0;x<8;x++)if(this.board[y][x]==='b')for(const m of this.moves(x,y))all.push({x,y,m});all.sort((a,b)=>(b.m.cx!=null)-(a.m.cx!=null));let a=all[0];if(a){this.board[a.m.y][a.m.x]='b';this.board[a.y][a.x]=null;if(a.m.cx!=null){this.board[a.m.cy][a.m.cx]=null;AudioEngine.play('failure');}}this.turn='r';}
 hasMove(side){for(let y=0;y<8;y++)for(let x=0;x<8;x++)if(this.board[y][x]===side&&this.moves(x,y).length)return true;return false;}
 update(){let r=this.board.flat().filter(v=>v==='r').length,b=this.board.flat().filter(v=>v==='b').length;if(!b||!this.hasMove('b')){this.rewardWin('Red Wins', 'Red Strategy Medal', 600);return;}if(!r||!this.hasMove('r')){this.gameOver('Black Wins');return;}this.updateHUD({Red:r,Black:b,Goal:'Remove/block black',Reward:'Red Strategy Medal',Turn:this.turn==='r'?'You':'AI'});}
 draw(){let c=this.ctx;for(let y=0;y<8;y++)for(let x=0;x<8;x++){c.fillStyle=(x+y)%2?'#4b2e2e':'#f1d6a8';c.fillRect(this.off.x+x*this.cell,this.off.y+y*this.cell,this.cell,this.cell);if(this.sel&&this.sel.x===x&&this.sel.y===y){c.fillStyle='rgba(255,255,0,.25)';c.fillRect(this.off.x+x*this.cell,this.off.y+y*this.cell,this.cell,this.cell);}let p=this.board[y][x];if(p){c.fillStyle=p==='r'?'#ff4d6d':'#111827';c.beginPath();c.arc(this.off.x+x*this.cell+29,this.off.y+y*this.cell+29,22,0,7);c.fill();}}}
}
document.addEventListener('DOMContentLoaded',()=>{window.currentGame=new CheckersClassic('checkers-classic','Checkers Classic');window.currentGame.start();});
