class MinesweeperGame extends BaseGame {
  constructor(){ super('minesweeper','Minesweeper Advanced'); this.cols=12; this.rows=12; this.cell=38; this.ox=170; this.oy=55; this.canvas.addEventListener('contextmenu', e=>e.preventDefault()); this.canvas.addEventListener('pointerdown', e=>this.click(e)); }
  reset(){ this.mines=22; this.revealed=0; this.grid=Array.from({length:this.rows},(_,y)=>Array.from({length:this.cols},(_,x)=>({x,y,mine:false,open:false,flag:false,n:0}))); let placed=0; while(placed<this.mines){ const c=this.grid[Math.floor(Math.random()*this.rows)][Math.floor(Math.random()*this.cols)]; if(!c.mine){ c.mine=true; placed++; } } for(const row of this.grid) for(const c of row) c.n=this.neighbors(c).filter(n=>n.mine).length; }
  neighbors(c){ const a=[]; for(let dy=-1;dy<=1;dy++) for(let dx=-1;dx<=1;dx++){ if(dx||dy){ const n=this.grid[c.y+dy]?.[c.x+dx]; if(n) a.push(n); } } return a; }
  click(e){ if(this.over||this.paused) return; const p=this.pointer(e); const x=Math.floor((p.x-this.ox)/this.cell), y=Math.floor((p.y-this.oy)/this.cell); const c=this.grid[y]?.[x]; if(!c) return; if(e.button===2 || this.input.isPressed('secondary')){ c.flag=!c.flag; AudioEngine.play('click'); } else this.open(c); this.updateHUD({Mines:this.mines, Revealed:this.revealed}); }
  open(c){ if(c.open||c.flag) return; c.open=true; this.revealed++; if(c.mine){ this.gameOver('Mine exploded'); return; } this.score+=5; if(c.n===0) this.neighbors(c).forEach(n=>this.open(n)); if(this.revealed===this.cols*this.rows-this.mines) this.win('Minefield cleared'); }
  update(){ this.updateHUD({Mines:this.mines, Revealed:this.revealed}); }
  draw(){ const c=this.ctx; c.font='bold 19px system-ui'; c.textAlign='center'; c.textBaseline='middle'; for(const row of this.grid) for(const cell of row){ const x=this.ox+cell.x*this.cell, y=this.oy+cell.y*this.cell; c.fillStyle=cell.open?'rgba(255,255,255,.16)':'rgba(124,92,255,.55)'; c.fillRect(x+2,y+2,this.cell-4,this.cell-4); if(cell.flag){ c.fillStyle='#ffd166'; c.fillText('⚑',x+this.cell/2,y+this.cell/2); } if(cell.open&&cell.mine){ c.fillStyle='#ff4d6d'; c.fillText('●',x+this.cell/2,y+this.cell/2); } else if(cell.open&&cell.n){ c.fillStyle='#18e0ff'; c.fillText(cell.n,x+this.cell/2,y+this.cell/2); } } }
}
window.currentGame = new MinesweeperGame(); window.addEventListener('DOMContentLoaded', () => currentGame.start());
