class Game2048 extends BaseGame {
  constructor(){ super('game-2048','2048 Animated'); this.size=4; this.cell=105; this.ox=190; this.oy=80; }
  reset(){ this.grid=Array.from({length:4},()=>Array(4).fill(0)); this.addTile(); this.addTile(); }
  addTile(){ const empty=[]; for(let y=0;y<4;y++) for(let x=0;x<4;x++) if(!this.grid[y][x]) empty.push({x,y}); if(empty.length){ const p=Utils.choice(empty); this.grid[p.y][p.x]=Math.random()<.9?2:4; } }
  slideRow(row){ const vals=row.filter(Boolean); let out=[]; let gained=0; for(let i=0;i<vals.length;i++){ if(vals[i]===vals[i+1]){ out.push(vals[i]*2); gained+=vals[i]*2; i++; } else out.push(vals[i]); } while(out.length<4) out.push(0); return {row:out,gained}; }
  move(dir){ const before=JSON.stringify(this.grid); let gained=0; const rotate = g => g[0].map((_,i)=>g.map(r=>r[i]).reverse()); const unrotate = g => g[0].map((_,i)=>g.map(r=>r[3-i])); let work=this.grid.map(r=>[...r]); if(dir==='up') work=rotate(work); if(dir==='down'){ work=rotate(work).map(r=>r.reverse()); } if(dir==='right') work=work.map(r=>r.reverse()); work=work.map(r=>{ const res=this.slideRow(r); gained+=res.gained; return res.row; }); if(dir==='right') work=work.map(r=>r.reverse()); if(dir==='up') work=unrotate(work); if(dir==='down') work=unrotate(work.map(r=>r.reverse())); this.grid=work; if(JSON.stringify(this.grid)!==before){ this.score+=gained; this.level=Math.max(...this.grid.flat()); this.addTile(); AudioEngine.play('click'); if(this.level>=2048) this.win('2048 reached'); if(!this.canMove()) this.gameOver('No more moves'); } this.updateHUD({BestTile:this.level}); }
  canMove(){ for(let y=0;y<4;y++) for(let x=0;x<4;x++) if(!this.grid[y][x] || this.grid[y][x]===this.grid[y][x+1] || this.grid[y][x]===this.grid[y+1]?.[x]) return true; return false; }
  handleDirection(d){ this.move(d); }
  draw(){ const c=this.ctx; c.fillStyle='rgba(255,255,255,.07)'; c.fillRect(this.ox-12,this.oy-12,4*this.cell+24,4*this.cell+24); c.textAlign='center'; c.textBaseline='middle'; c.font='bold 32px system-ui'; for(let y=0;y<4;y++) for(let x=0;x<4;x++){ const v=this.grid[y][x]; c.fillStyle=v?`hsl(${Math.log2(v)*28},80%,55%)`:'rgba(255,255,255,.08)'; c.fillRect(this.ox+x*this.cell+6,this.oy+y*this.cell+6,this.cell-12,this.cell-12); if(v){ c.fillStyle='#08101f'; c.fillText(v,this.ox+x*this.cell+this.cell/2,this.oy+y*this.cell+this.cell/2); } } }
}
window.currentGame = new Game2048(); window.addEventListener('DOMContentLoaded', () => currentGame.start());
