class SnakeGame extends BaseGame {
  constructor() { super('snake', 'Snake Ultimate'); this.cell = 24; this.cols = 25; this.rows = 20; this.offsetX = 100; this.offsetY = 60; }
  reset() { this.snake = [{x:12,y:10},{x:11,y:10},{x:10,y:10}]; this.dir = {x:1,y:0}; this.pending = {x:1,y:0}; this.food = this.spawnFood(); this.step = 0; this.speed = 0.115; }
  spawnFood() { let p; do { p = {x:Math.floor(Math.random()*this.cols), y:Math.floor(Math.random()*this.rows)}; } while (this.snake.some(s=>s.x===p.x&&s.y===p.y)); return p; }
  handleDirection(d) { const map = {left:{x:-1,y:0}, right:{x:1,y:0}, up:{x:0,y:-1}, down:{x:0,y:1}}; const nd = map[d]; if (nd && nd.x !== -this.dir.x && nd.y !== -this.dir.y) this.pending = nd; }
  update(dt) { this.step += dt; if (this.step < this.speed) return; this.step = 0; this.dir = this.pending; const head = {x:this.snake[0].x + this.dir.x, y:this.snake[0].y + this.dir.y}; if (head.x<0||head.y<0||head.x>=this.cols||head.y>=this.rows||this.snake.some(s=>s.x===head.x&&s.y===head.y)) return this.gameOver('Snake crashed'); this.snake.unshift(head); if (head.x===this.food.x && head.y===this.food.y) { this.score += 10; this.food = this.spawnFood(); this.speed = Math.max(.055, this.speed-.003); this.particles.push(...Utils.makeParticles(this.offsetX+head.x*this.cell+12, this.offsetY+head.y*this.cell+12, 14, '#36e28f')); AudioEngine.play('coin'); } else this.snake.pop(); this.level = Math.floor(this.score/80)+1; this.updateHUD({Length:this.snake.length}); }
  draw() { const c=this.ctx; c.fillStyle='rgba(255,255,255,.04)'; c.fillRect(this.offsetX,this.offsetY,this.cols*this.cell,this.rows*this.cell); c.strokeStyle='rgba(255,255,255,.05)'; for(let x=0;x<=this.cols;x++){c.beginPath();c.moveTo(this.offsetX+x*this.cell,this.offsetY);c.lineTo(this.offsetX+x*this.cell,this.offsetY+this.rows*this.cell);c.stroke();} for(let y=0;y<=this.rows;y++){c.beginPath();c.moveTo(this.offsetX,this.offsetY+y*this.cell);c.lineTo(this.offsetX+this.cols*this.cell,this.offsetY+y*this.cell);c.stroke();} c.fillStyle='#ff4d6d'; c.beginPath(); c.arc(this.offsetX+this.food.x*this.cell+12,this.offsetY+this.food.y*this.cell+12,9,0,Math.PI*2); c.fill(); this.snake.forEach((s,i)=>{ c.fillStyle = i===0 ? '#18e0ff' : '#36e28f'; c.fillRect(this.offsetX+s.x*this.cell+2,this.offsetY+s.y*this.cell+2,this.cell-4,this.cell-4); }); }
}
window.currentGame = new SnakeGame(); window.addEventListener('DOMContentLoaded', () => currentGame.start());
