class BomberArena extends BaseGame{
  rewardWin(message, reward, bonus=250){ if(this.over) return; this.score += bonus; StorageManager.saveAchievement(this.gameId, 'reward-'+reward.toLowerCase().replace(/[^a-z0-9]+/g,'-'), 'Reward: '+reward); this.win(message + ' — Reward: ' + reward); }

 reset(){this.w=15;this.h=11;this.cell=42;this.off={x:85,y:75};this.grid=[];for(let y=0;y<this.h;y++){this.grid[y]=[];for(let x=0;x<this.w;x++)this.grid[y][x]=(x===0||y===0||x===this.w-1||y===this.h-1||(x%2===0&&y%2===0))?'wall':(Math.random()<.28?'crate':'');}this.grid[1][1]=this.grid[1][2]=this.grid[2][1]='';this.player={x:1,y:1,cd:0};this.bombs=[];this.flames=[];this.enemies=[{x:13,y:9,t:0},{x:13,y:1,t:0},{x:1,y:9,t:0}];this.score=0;this.lives=3;}
 block(x,y){return this.grid[y]?.[x]&&this.grid[y][x]!=='';}
 handleDirection(d){let p=this.player,dx={left:-1,right:1,up:0,down:0}[d],dy={left:0,right:0,up:-1,down:1}[d];if(!this.block(p.x+dx,p.y+dy)&&!this.bombs.some(b=>b.x===p.x+dx&&b.y===p.y+dy)){p.x+=dx;p.y+=dy;AudioEngine.play('click');}}
 handleAction(a){if(a==='action'&&this.player.cd<=0&&!this.bombs.some(b=>b.x===this.player.x&&b.y===this.player.y)){this.bombs.push({x:this.player.x,y:this.player.y,t:2});this.player.cd=.4;AudioEngine.play('shoot');}}
 explode(b){let cells=[[b.x,b.y]];for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]])for(let i=1;i<=2;i++){let x=b.x+dx*i,y=b.y+dy*i;if(this.grid[y]?.[x]==='wall')break;cells.push([x,y]);if(this.grid[y]?.[x]==='crate'){this.grid[y][x]='';this.score+=25;break;}}for(const [x,y] of cells)this.flames.push({x,y,t:.45});this.enemies=this.enemies.filter(e=>{let hit=cells.some(([x,y])=>x===e.x&&y===e.y);if(hit){this.score+=100;AudioEngine.play('explosion');}return !hit;});if(cells.some(([x,y])=>x===this.player.x&&y===this.player.y)){this.lives--;AudioEngine.play('failure');if(this.lives<=0)this.gameOver('Bombed Out');}}
 update(dt){this.player.cd-=dt;for(const b of this.bombs)b.t-=dt;for(const b of this.bombs.filter(b=>b.t<=0))this.explode(b);this.bombs=this.bombs.filter(b=>b.t>0);this.flames=this.flames.filter(f=>(f.t-=dt)>0);for(const e of this.enemies){e.t-=dt;if(e.t<=0){e.t=.35;let dirs=[[1,0],[-1,0],[0,1],[0,-1]].sort(()=>Math.random()-.5);dirs.sort((a,b)=>Math.abs(e.x+a[0]-this.player.x)+Math.abs(e.y+a[1]-this.player.y)-Math.abs(e.x+b[0]-this.player.x)-Math.abs(e.y+b[1]-this.player.y));for(const [dx,dy]of dirs)if(!this.block(e.x+dx,e.y+dy)){e.x+=dx;e.y+=dy;break;}}if(e.x===this.player.x&&e.y===this.player.y){this.lives--;this.player.x=1;this.player.y=1;if(this.lives<=0)this.gameOver('Bot Collision');}}if(!this.enemies.length)this.rewardWin('Arena Cleared', 'Arena Champion Belt');this.updateHUD({Enemies:this.enemies.length,Goal:'Defeat all bots',Reward:'Arena Champion Belt'});}
 draw(){const c=this.ctx,cs=this.cell,o=this.off;for(let y=0;y<this.h;y++)for(let x=0;x<this.w;x++){let px=o.x+x*cs,py=o.y+y*cs;c.fillStyle='#0b1730';c.fillRect(px,py,cs-2,cs-2);if(this.grid[y][x]==='wall'){c.fillStyle='#334b8f';c.fillRect(px+3,py+3,cs-8,cs-8);}if(this.grid[y][x]==='crate'){c.fillStyle='#a9703b';c.fillRect(px+6,py+6,cs-12,cs-12);}}for(const b of this.bombs){c.fillStyle='#111';c.beginPath();c.arc(o.x+b.x*cs+cs/2,o.y+b.y*cs+cs/2,13+Math.sin(b.t*12)*2,0,7);c.fill();}for(const f of this.flames){c.fillStyle='rgba(255,80,60,.85)';c.fillRect(o.x+f.x*cs+5,o.y+f.y*cs+5,cs-12,cs-12);}c.fillStyle='#18e0ff';c.fillRect(o.x+this.player.x*cs+9,o.y+this.player.y*cs+9,cs-20,cs-20);c.fillStyle='#ff4d6d';for(const e of this.enemies)c.fillRect(o.x+e.x*cs+8,o.y+e.y*cs+8,cs-18,cs-18);}
}
document.addEventListener('DOMContentLoaded',()=>{window.currentGame=new BomberArena('bomber-arena','Bomber Arena');window.currentGame.start();});
